#!/usr/bin/env bash
#comment
sudo sed -i '/^.*:80 default_server;.*/a location /redirect_me {rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 redirect;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
