#!/usr/bin/env bash
#install balance loader
sudo apt-get update -y
sudo apt-get install -y haproxy
sudo echo 'frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 4384-web-02 35.175.196.152:80 check
        server 4384-web-01 34.201.143.161:80 check' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
