#!/usr/bin/env bash
# commands to automate your fix
sudo service nginx stop
sed -i 's/listen 8080 default_server;/listen 80 default_server/g' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default
sudo service nginx start
