#!/usr/bin/env bash
#comment
echo "$$" > /var/run/myscript.pid
function kind
{
    echo "I hate the kill command"
}
function control_c
{
    echo "Y U no love me?!"
    rm /var/run/myscript.pid
    exit
}
function quit
{
    rm /var/run/myscript.pid
    exit
}
trap quit SIGQUIT
trap control_c SIGTERM
trap kind SIGINT
while :
do
    echo "To infinity and beyond"
    sleep 2
done
