#!/usr/bin/env bash
#comment
echo "$$" > /var/run/myscript.pid
function kind
{
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit
}
function control_c
{
    echo "Y U no love me?!"
}
function quit
{
    rm /var/run/myscript.pid
    exit
}
trap quit SIGQUIT
trap control_c SIGINT
trap kind SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
