#!/usr/bin/env bash
#comment
if [[ $1 -eq "start" ]]
then
    ./manage_my_process & echo "$$" > /var/run/my_process.pid & echo "manage_my_process started"
elif [[ $1 -eq "stop" ]]
then
    kill "$( cat /var/run/my_process.pid)" & rm /var/run/my_process.pid & echo "manage_my_process stopped"
elif [[ $1 -e "restar" ]]
then
    kill "$( cat /var/run/my_process.pid)" & rm /var/run/my_process.pid & ./manage_my_process & echo "$$" > /var/run/my_process.pid & echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
