#!/usr/bin/env bash
#print luck
x=1 
until [[ $x -gt 10 ]]
do
    if [ $x -eq 4 ] 
    then
        echo "bad luck"
    elif [ $x -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi  
    ((x++))
done     
