#!/usr/bin/env bash
#comment
x=1 
while [[ $x -le 20 ]]
do
    echo "$x"
    if [ $x -eq 4 ] 
    then
        echo "bad luck from china"
    elif [ $x -eq 9 ] 
    then
        echo "bad luck from Japan"
    elif [ $x -eq 17 ]
    then
        echo "bad luck from italy"
    fi  
        ((x++))
done    
