#!/usr/bin/env bash
#comment
x=1 
while [[ $x -le 20 ]]
do
    case $x in
        4)  echo $x
            echo "bad luck from china"
            ;;
        9)  echo $x
            echo "bad luck from Japan"
            ;;
        17) echo $x
            echo "bad luck from italy"
            ;;
        *)  echo $x
    esac
        ((x++))
done    
