#!/usr/bin/env bash
#change owner and port
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
sudo -H -u nginx bash -c  '/etc/init.d/nginx start'
